"use client";
import React, { useState, useEffect } from "react";
const QUOTES: string[] = [
  // include 100 short trading/game quotes as strings. Example:
  "Play smart, not hard",
  "Risk managed wins",
  "Live Love Laugh",
  "Dreams Come True",
  "Trust The Process",
  "Keep Moving Forward",
  "Love Conquers All",
  "Time Heals Everything",
  "Never Give Up",
  "Believe In Yourself",
  "Change Is Good",
  "Knowledge Is Power",
  "Actions Speak Louder",
  "Follow Your Heart",
  "Life Is Beautiful",
  "Choose Your Battles",
  "Seize The Day",
  "Hope Never Dies",
  "Focus And Win",
  "Embrace The Journey",
  "Silence Is Golden",
  "Patience Pays Off",
  "Good Things Come",
  "Make It Happen",
  "Stay The Course",
  "Enjoy The Ride",
  "Let It Be",
  "Every Moment Matters",
  "Failure Fuels Growth",
  "Gratitude Changes Everything",
  "Create Your Reality",
  "Practice Makes Perfect",
  "Learn From Yesterday",
  "Stay In Motion",
  "Truth Sets Free",
  "Small Steps Matter",
  "Be The Change",
  "Rise And Shine",
  "Love Without Limits",
  "Kindness Is Free",
  "Work Brings Reward",
  "Energy Flows Where",
  "Never Stop Learning",
  "Push Through Fear",
  "Calm Brings Clarity",
  "Consistency Builds Trust",
  "Faith Moves Mountains",
  "Stay Strong Always",
  "Break Your Limits",
  "Hard Work Wins",
  "Peace Over Chaos",
  "Chase Your Dreams",
  "Mind Over Matter",
  "Focus On Growth",
  "Respect Builds Relationships",
  "Failure Teaches Lessons",
  "Stay Humble Always",
  "Life Goes On",
  "Control Your Mind",
  "Happiness Is Homemade",
  "Keep The Faith",
  "Love Heals All",
  "Discipline Equals Freedom",
  "Seek The Truth",
  "Strength In Unity",
  "Celebrate Small Wins",
  "Protect Your Peace",
  "Enjoy Simple Things",
  "Turn Pain Purpose",
  "Be Fearless Always",
  "Actions Create Results",
  "Time Flies Fast",
  "Listen More Often",
  "Choose Happiness Daily",
  "Never Lose Hope",
  "Live Without Regret",
  "Seek New Adventures",
  "Gratitude Attracts Joy",
  "Love Creates Magic",
  "Stay Curious Always",
  "Effort Brings Success",
  "Progress Over Perfection",
  "Enjoy Every Breath",
  "Keep Dreams Alive",
  "Serve With Love",
  "Win With Grace",
  "Cherish Loved Ones",
  "Patience Is Strength",
  "Think Before Speaking",
  "Stay True Always",
  "Lead With Integrity",
  "Forgive And Forget",
  "Love Without Fear",
  "Protect Your Energy",
  "Learn Teach Inspire",
  "Observe Don’t Judge",
  "Share Your Light",
  "Listen Without Judgement",
  "Value Your Time",
  "Trust Your Journey",
  "Believe In Magic",
  "Keep Heart Open",
  "Respect Your Boundaries",
];

export default function QuotesRotator() {
  const [i, setI] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setI((s) => (s + 1) % QUOTES.length), 5000);
    return () => clearInterval(id);
  }, []);
  return <div className="quotes text-sm italic">{QUOTES[i]}</div>;
}
